baseURL = "https://jendiamond.github.io/develedge"
themeDir = "theme"
publishDir = "docs"
languageCode = "en-us"
title = "Developer Ledger"
theme = "kube"

description = "Resources by & for Jen Diamond"
Paginate = 10
[Params]
  RSSLink = "/index.xml"
  author = "Jen Diamond"
  github = "jendiamond"
  twitter = "jendiamond" 
  email = "thejendiamond@gmail.com"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
